name: Deploy umrah-mgmt

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy Code & Migrate
        run: |
          if [ ! -d "/home/umrah-mgmt/.git" ]; then
            echo "Git repository not found. Initializing clone..."
            git clone https://github.com/khalilksa33/umrah-mgmt /home/umrah-mgmt || (sudo rm -rf /home/umrah-mgmt && sudo mkdir -p /home/umrah-mgmt && sudo chown -R $(whoami):$(whoami) /home/umrah-mgmt && git clone https://github.com/khalilksa33/umrah-mgmt /home/umrah-mgmt)
          fi
          cd /home/umrah-mgmt
          git fetch origin main
          git reset --hard origin/main
          /home/frappe/.local/bin/bench --site 26i.uk migrate
          /home/frappe/.local/bin/bench build
          /home/frappe/.local/bin/bench restart
